apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: app-container
    image: gcr.io/kuar-demo/kuard-amd64:1
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
