apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  template:
    spec:
      volumes:
        - name: data-input
          gcePersistentDisk:
            pdName: pd-name
            fsType: xfs
      containers:
        - name: app
          image: google/cloud-sdk:275.0.0-alpine
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "gsutil rsync -r gs://glow-sportradar/ /data/input"
          volumeMounts:
            - name: data-input
              mountPath: /data/input
      restartPolicy: Never
